"""Database package for the Telegram Education Bot."""

from .models import (
    init_db,
    get_user,
    add_user,
    update_user_group,
    update_user_name,
    update_user_role,
    toggle_notifications,
    get_users_for_group,
    get_users_by_name,
    get_users_by_role,
    get_group_leader,
    add_event,
    get_events,
    get_all_events,
    get_events_for_date,
    edit_event,
    delete_event,
    send_message,
    get_messages,
    mark_message_read,
    get_unread_count,
    get_subject_info,
    get_stats,
    get_all_users,
    UserRole,
)

__all__ = [
    "init_db",
    "get_user",
    "add_user",
    "update_user_group",
    "update_user_name",
    "update_user_role",
    "toggle_notifications",
    "get_users_for_group",
    "get_users_by_name",
    "get_users_by_role",
    "get_group_leader",
    "add_event",
    "get_events",
    "get_all_events",
    "get_events_for_date",
    "edit_event",
    "delete_event",
    "send_message",
    "get_messages",
    "mark_message_read",
    "get_unread_count",
    "get_subject_info",
    "get_stats",
    "get_all_users",
    "UserRole",
]
